config/routes.rb
Rails.application.routes.draw do
  get 'pages/contact'

  get 'pages/home'

  get 'pages/about'

  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-fixed-top headroom" >
  <div class="container">
    <div class="navbar-header">
      <!-- Button for smallest screens -->
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>

      <a class="navbar-brand" href="index.html"><img src="../images/logo_1289630_web.jpg" alt="Ruby & Bootstrap"></a>

    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav pull-right">
        <li class="active"><%= link_to "Home", pages_home_path %></li>

        <li><%= link_to "About", pages_about_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">More Pages <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="sidebar-left.html">Left Sidebar</a></li>
            <li class="active"><a href="sidebar-right.html">Right Sidebar</a></li>
          </ul>
        </li>
        <li><%= link_to "Contact", pages_contact_path %></li>

        <li> <%= button_to('Sign In', new_user_session_path, :class => 'btn btn-large btn-primary')  %> </li>




      </ul>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <%= render 'layouts/navigation_links' %>

        </ul>
      </div>
    </div><!--/.nav-collapse -->
  </div>
</div>
<!-- /.navbar -->

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>


<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport"    content="width=device-width, initial-scale=1.0">


  <title><%= content_for?(:title) ? yield(:title) : "Shopxsite" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Shopxsite" %>">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <title> bootstrap template by GetTemplate</title>

  <link rel="shortcut icon" href="gt_favicon.png">

  <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
  <link rel="stylesheet" href="bootstrap.min.css">
  <link rel="stylesheet" href="font-awesome.min.css">

  <!-- Custom styles for our template -->
  <link rel="stylesheet" href="bootstrap-theme.css" media="screen" >
  <link rel="stylesheet" href="main.css">FFFFFF

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="html5shiv.js"></script>
  <script src="respond.min.js"></script>
  <![endif]-->
</head>

<body class="home">

<!-- Header -->
<header id="head">
  <div class="container">
    <div class="row">
      <h1 class="lead"><b>AWESOME, CUSTOMIZABLE, FREE</b></h1>
      <p class="tagline"><b>RUBOOT: Free Ruby & Bootstrap template</b> <a href='http://rubyonrails.org/'></a></p>

    </div>
  </div>
</header>
<!-- /Header -->

<!-- Intro -->
<div class="container text-center">
  <br> <br>
  <h2 class="thin">The best place to tell people why they are here</h2>
  <p class="text-muted">
    <%= link_to image_tag("logo_1289630_web.jpg", alt: "Rails logo"), 'http://rubyonrails.org/' %>
  </p>
  <header>
    <%= render 'layouts/navigation' %>
  </header>
  <main role="main">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </main>




</div>
<!-- /Intro-->

<!-- Highlights - jumbotron -->
<div class="jumbotron top-space">
  <div class="container">

    <h3 class="text-center thin">Reasons to use this template</h3>

    <div class="row">
      <div class="col-md-3 col-sm-6 highlight">
        <div class="h-caption"><h4><i class="fa fa-cogs fa-5"></i>Bootstrap-powered</h4></div>
        <div class="h-body text-center">
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque aliquid adipisci aspernatur. Soluta quisquam dignissimos earum quasi voluptate. Amet, dignissimos, tenetur vitae dolor quam iusto assumenda hic reprehenderit?</p>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 highlight">
        <div class="h-caption"><h4><i class="fa fa-flash fa-5"></i>Fat-free</h4></div>
        <div class="h-body text-center">
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores, commodi, sequi quis ad fugit omnis cumque a libero error nesciunt molestiae repellat quos perferendis numquam quibusdam rerum repellendus laboriosam reprehenderit! </p>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 highlight">
        <div class="h-caption"><h4><i class="fa fa-heart fa-5"></i>Creative Commons</h4></div>
        <div class="h-body text-center">
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem, vitae, perferendis, perspiciatis nobis voluptate quod illum soluta minima ipsam ratione quia numquam eveniet eum reprehenderit dolorem dicta nesciunt corporis?</p>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 highlight">
        <div class="h-caption"><h4><i class="fa fa-smile-o fa-5"></i>Author's support</h4></div>
        <div class="h-body text-center">
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias, excepturi, maiores, dolorem quasi reprehenderit illo accusamus nulla minima repudiandae quas ducimus reiciendis odio sequi atque temporibus facere corporis eos expedita? </p>
        </div>
      </div>
    </div> <!-- /row  -->

  </div>
</div>
<!-- /Highlights -->

<!-- container -->
<div class="container">

  <h2 class="text-center top-space">Frequently Asked Questions</h2>
  <br>

  <div class="row">
    <div class="col-sm-6">
      <h3>Which code editor would you recommend?</h3>
      <p>I'd highly recommend you <a href="http://www.sublimetext.com/">Sublime Text</a> - a free to try text editor which I'm using daily. Awesome tool!</p>
    </div>
    <div class="col-sm-6">
      <h3>Nice header. Where do I find more images like that one?</h3>
      <p>
        Well, there are thousands of stock art galleries, but personally,
        I prefer to use photos from these sites: <a href="http://unsplash.com">Unsplash.com</a>
        and <a href="http://www.flickr.com/creativecommons/by-2.0/tags/">Flickr - Creative Commons</a></p>
    </div>
  </div> <!-- /row -->

  <div class="row">
    <div class="col-sm-6">
      <h3>Can I use it to build a site for my client?</h3>
      <p>
        Yes, you can. You may use this template for any purpose, just don't forget about the <a href="http://creativecommons.org/licenses/by/3.0/">license</a>,
        which says: "You must give appropriate credit", i.e. you must provide the name of the creator and a link to the original template in your work.
      </p>
    </div>
    <div class="col-sm-6">
      <h3>Can you customize this template for me?</h3>
      <p>Yes, I can. Please drop me a line to sergey-at-pozhilov.com and describe your needs in details. Please note, my services are not cheap.</p>
    </div>
  </div> <!-- /row -->

  <div class="jumbotron top-space">
    <h4>Dicta, nostrum nemo soluta sapiente sit dolor quae voluptas quidem doloribus recusandae facere magni ullam suscipit sunt atque rerum eaque iusto facilis esse nam veniam incidunt officia perspiciatis at voluptatibus. Libero, aliquid illum possimus numquam fuga.</h4>
    <p class="text-right"><a class="btn btn-primary btn-large">Learn more »</a></p>
  </div>

</div>	<!-- /container -->

<!-- Social links. @TODO: replace by link/instructions in template -->
<section id="social">
  <div class="container">
    <div class="wrapper clearfix">
      <!-- AddThis Button BEGIN -->
      <div class="addthis_toolbox addthis_default_style">
        <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
        <a class="addthis_button_tweet"></a>
        <a class="addthis_button_linkedin_counter"></a>
        <a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
      </div>
      <!-- AddThis Button END -->
    </div>
  </div>
</section>
<!-- /social links -->


<footer id="footer" class="top-space">

  <div class="footer1">
    <div class="container">
      <div class="row">

        <div class="col-md-3 widget">
          <h3 class="widget-title">Contact</h3>
          <div class="widget-body">
            <p>+234 23 9873237<br>
              <a href="mailto:#">some.email@somewhere.com</a><br>
              <br>
              234 Hidden Pond Road, Ashland City, TN 37015
            </p>
          </div>
        </div>

        <div class="col-md-3 widget">
          <h3 class="widget-title">Follow me</h3>
          <div class="widget-body">
            <p class="follow-me-icons">
              <a href=""><i class="fa fa-twitter fa-2"></i></a>
              <a href=""><i class="fa fa-dribbble fa-2"></i></a>
              <a href=""><i class="fa fa-github fa-2"></i></a>
              <a href=""><i class="fa fa-facebook fa-2"></i></a>
            </p>
          </div>
        </div>

        <div class="col-md-6 widget">
          <h3 class="widget-title">Text widget</h3>
          <div class="widget-body">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi, dolores, quibusdam architecto voluptatem amet fugiat nesciunt placeat provident cumque accusamus itaque voluptate modi quidem dolore optio velit hic iusto vero praesentium repellat commodi ad id expedita cupiditate repellendus possimus unde?</p>
            <p>Eius consequatur nihil quibusdam! Laborum, rerum, quis, inventore ipsa autem repellat provident assumenda labore soluta minima alias temporibus facere distinctio quas adipisci nam sunt explicabo officia tenetur at ea quos doloribus dolorum voluptate reprehenderit architecto sint libero illo et hic.</p>
          </div>
        </div>

      </div> <!-- /row of widgets -->
    </div>
  </div>

  <div class="footer2">
    <div class="container">
      <div class="row">

        <div class="col-md-6 widget">
          <div class="widget-body">
            <p class="simplenav">
              %# add navigation links to this file %>
              <% if user_signed_in? %>
                <li><%= link_to 'Edit account', edit_user_registration_path %></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
            <% else %>
                <li><%= link_to 'Sign in', new_user_session_path %></li>
                <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <% end %>
            <% if user_signed_in? %>
                <li><%= link_to 'Users', users_path %></li>
            <% end %>
            </p>
          </div>
        </div>

        <div class="col-md-6 widget">
          <div class="widget-body">
            <p class="text-right">
              Copyright &copy; 2014, Your name. Designed by <a href="http://gettemplate.com/" rel="designer">gettemplate</a>
            </p>
          </div>
        </div>

      </div> <!-- /row of widgets -->
    </div>
  </div>

</footer>





<!-- JavaScript libs are placed at the end of the document so the pages load faster -->
<script src="jquery.min.js"></script>
<script src="bootstrap.min.js"></script>
<script src="headroom.min.js"></script>
<script src="jQuery.headroom.min.js"></script>
<script src="template.js"></script>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>